### ISSUE TITLE
Typescript Definition File Best Practices?

### ISSUE THREAD

**Issue by evanlemke** [Mohamed-Kaizen/unplugin-svelte-components#12]
```
// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
```

Can you elaborate on this a bit? The `components.d.ts` is auto-generated and constantly changing resulting in merge conflicts.  What is the benefit of committing it?

**Comment by Mohamed-Kaizen** [comment]
let say you have :

```ts
// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
    const Dialog: typeof import("./components/dialog.svelte")["default"]
    const Nav: typeof import("./components/nav/index.svelte")["default"]
}

export {}
```

and you commit this with these two components, so..as long you don't add any other components ..unplugin-svelte-components will generate the same **components.d.ts** so...there will be no git update or anything.

Let say you added a component called **button.svelte** inside the component folder....then **unplugin-svelte-components** will generate it:

```ts
// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
    const Button: typeof import("./components/button.svelte")["default"]
    const Dialog: typeof import("./components/dialog.svelte")["default"]
    const Nav: typeof import("./components/nav/index.svelte")["default"]
}

export {}
```
when new component is added it , git will tell you the file has been update it and you need to commit it.


**what is the benefit**

well....when  you or someone else review the project in github or in any non-editor platform, they will see a lot of components without the import statement ...so...the **components.d.ts** is like import map.
