### ISSUE TITLE
Error when components have a `<style>` tag

### ISSUE THREAD

**Issue by Guz013** [Mohamed-Kaizen/unplugin-svelte-components#16]
Apparently, when a page has a `<style>` tag, the plugin injects the `<script>` tag with the imports on the wrong place.
![image](https://github.com/Mohamed-Kaizen/unplugin-svelte-components/assets/43732358/9b2a8655-e4fb-43bc-a333-58c423dfb94b)
> Yes, the file being auto-imported is a SVG file, but with the [`@poppanator/sveltekit-svg`](https://github.com/poppa/sveltekit-svg) package it can be imported as a Svelte component. This error also affects standard components.

I was able to replicate the error on the SvelteKit's demo app, just installing the plugin makes it throw an error. Link to the example/replication: https://stackblitz.com/edit/unplugin-svelte-components-issue-16.

**Comment by Guz013** [comment]
Don't know if this can be related, I wasn't able to replicate this issue on Stackblitz yet, but when a component/page doesn't have a `<script>` tag it throws this different error:

![image](https://github.com/Mohamed-Kaizen/unplugin-svelte-components/assets/43732358/ec11c305-df30-4658-a522-b905d513a63a)

<details>
<summary>
This said component looks like this:
</summary>

> It uses [UnoCSS](https://unocss.dev) and [mdsvex](https://mdsvex.com/). I don't know if they can influence is this issue, but doesn't looks like it when the wrongly placed `<script>` tag ends up inside the `<section>` tag.
> Even ignoring some type errors when placing mdsvex, vite preprocessor and/or the svelte preprocessor in the `config.preprocess` the error still occurs.

```svelte
<section un-max-w="60ch" un-m="y-auto" un-font="cal">
  <figure
    un-w="5ch"
    un-justify-self="lg:end center"
    un-place-self="lg:end center"
    un-m="0"
  >
    <figcaption un-hidden>Logo Light</figcaption>
    <LogoLightSvg /> <!-- component being auto-imported... -->
  </figure>

  <!-- ... -->

  <hr un-w="10ch" un-m="y-5" un-border="gray1 solid 1" />

  <div>
    <a href="https://guz.one">
      <figure
        un-w="5ch"
        un-text="dark:white"
        un-justify-self="lg:end center"
        un-place-self="lg:end center"
        un-m="0"
      >
        <figcaption un-hidden>Logo</figcaption>
        <Logo013Svg /> <!-- component being auto-imported... -->
      </figure>
    </a>
  </div>
</section>
```

</details>

**Comment by Mohamed-Kaizen** [comment]
> I was able to replicate the error on the SvelteKit's demo app, just installing the plugin makes it throw an error. Link to the example/replication: https://stackblitz.com/edit/unplugin-svelte-components-issue-16.

I did run the reproduction and yea there is an error 
![image](https://github.com/Mohamed-Kaizen/unplugin-svelte-components/assets/35686076/912c0a8b-1421-4fc2-a56a-fa987a126816)

so i checked the `vite.config.ts`:

```ts

import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';
import SvelteComponents from 'unplugin-svelte-components/vite';

export default defineConfig({
	plugins: [
		SvelteComponents({
			include: [
				/\.svelte/,
				/\.svelte\?svelte/,
			],
			dirs: [
				'./src/**/*',
			],
			dts: './src/components.d.ts',
		}),
		sveltekit()
	]
});
```

the issue is in the include, so if you remove it or changed into this :

```ts
export default defineConfig({
	plugins: [
		SvelteComponents({
			include: [
				/\.svelte$/,
			],
			dirs: [
				'./src/**/*',
			],
			dts: './src/components.d.ts',
		}),
		sveltekit()
	]
});
```
The code will run  and the components will be auto imported.

And by the way you don't need to do `'./src/**/*'`, `./src` will work fine, although `'./src/**/*'` will not break the plugin

**Comment by Guz013** [comment]
Oh, sorry about that 😅 

_I probably should have checked every character again, it's not the first time that I stumble an issue because of one simple character._

I'll be closing the issue.

---

If you don't mind, there's an explanation for why this happens? I know that the `$` indicates the end of a string, but it seems odd that because of it this error would occur, I thought that the regex was just to match the file path of the component/file being searched. *Probably why, when searching the source-code of the plugin to know why this happened, I wasn't able to find it.*

And the `'./src/**/*'` instead of `./src` is mostly because of familiarity/“muscular memory”.

---

Thanks for the help and the time, if I stumble on some another, issue I'll check a little more before opening an issue!

**Comment by Mohamed-Kaizen** [comment]
> If you don't mind, there's an explanation for why this happens? I know that the `$` indicates the end of a string, but it seems odd that because of it this error would occur, I thought that the regex was just to match the file path of the component/file being searched. _Probably why, when searching the source-code of the plugin to know why this happened, I wasn't able to find it._

well...honestly....i don't understand regex...i recently found package called [magic-regexp](https://regexp.dev/)..so i used that to create most of my regex or use Github Copilot

**Comment by Guz013** [comment]
> well...honestly....i don't understand regex...i recently found package called [magic-regexp](https://regexp.dev/)..so i used that to create most of my regex or use Github Copilot

Understandable 😅, thanks for your time and help!
