### ISSUE TITLE
I have upgraded to 0.2.9, but I am still encountering the same error.

### ISSUE THREAD

**Issue by muweigg** [Mohamed-Kaizen/unplugin-svelte-components#19]
Thank you for your work.
I have upgraded to 0.2.9, but I am still encountering the same error.

> If you have updated to version 0.2.9 or above, you can ignore the above solution. This plugin will now automatically ignore pre-defined components in imports declarations.

Log:
[plugin:vite-plugin-svelte] /src/routes/(default)/+page.svelte:5:8 Identifier 'Link' has already been declared
/Users/mui/Projects/svelte-template/src/routes/(default)/+page.svelte:2:1
3 | import Notice from "/Users/mui/Projects/svelte-template/src/lib/components/common/Notice.svelte"
4 | import Link from "/Users/mui/Projects/svelte-template/src/lib/components/common/Link.svelte"
5 | import Link from '$lib/components/common/Link.svelte'
^
6 | import Notice from '$lib/components/common/Notice.svelte'
7 | import {lazy} from '$lib/actions/lazy.js'

**Comment by Mohamed-Kaizen** [comment]
Can create a minimal reproduction in [stackblitz](https://stackblitz.com/) or [sveltelab](https://www.sveltelab.dev/)

**Comment by muweigg** [comment]
> Can create a minimal reproduction in [stackblitz](https://stackblitz.com/) or [sveltelab](https://www.sveltelab.dev/)

The demo is here [stackblitz](https://stackblitz.com/edit/sveltejs-kit-template-default-t51jyr).

It doesn't work. >_<
Log:
[vite-plugin-svelte] /src/routes/(default)/+page.svelte:3:0 'Link' is not defined

**Comment by muweigg** [comment]
Updating to the latest version now works fine, which is really cool.
