### ISSUE TITLE
'ComponentName' is not definedsvelte(missing-declaration)

### ISSUE THREAD

**Issue by hartwm** [Mohamed-Kaizen/unplugin-svelte-components#2]
This is probably less of a bug and more of a typescript newbie question. I am using your package successfully to autoimport in sveltekit and its generating components.d.ts, however, my VS code is still showing errors all over the place. The code compiles and works, but it's unusable in terms of visual feedback. Am I missing something else I need to do?

**Comment by Mohamed-Kaizen** [comment]
The d.ts file will silence errors by typescript that it cannot find the module. The mentioned warning here is from the Svelte compiler, which cannot be silenced like this. There currently isn't a way to silence a warning across svelte-check.

**Comment by hallefsantos** [comment]
@Mohamed-Kaizen did you find a solution for that? I'm having the same error.

**Comment by Mohamed-Kaizen** [comment]
The only way to silence the warning in VS code, is this 👇

![image](https://user-images.githubusercontent.com/35686076/204524926-ae3226c9-618b-4d97-b524-1e0c64acee35.png)
