### ISSUE TITLE
mdsvx fails autoimport

### ISSUE THREAD

**Issue by ryoppippi** [Mohamed-Kaizen/unplugin-svelte-components#23]
I tried to use mdsvx and unplugin-svelte-comonent, but because of the order of the process, the autoimport didn't work for markdown files.

**Comment by Mohamed-Kaizen** [comment]
When I made unplugin-svelte-component, I didn't think about using mdsvx. So it's okay if it doesn't work right now. I know it would be helpful, but I can't add it right now. Maybe I can add it later, but not soon. If you want to help, you can send me a PR :)
