### ISSUE TITLE
Remove Component.story.svelte from auto import

### ISSUE THREAD

**Issue by hallefsantos** [Mohamed-Kaizen/unplugin-svelte-components#4]
Hi @Mohamed-Kaizen , is there a way to remove these files from auto-import? I've tried to use `exclude`, but didn't work.

![Screen Shot 2022-12-21 at 09 51 14](https://user-images.githubusercontent.com/20205767/208909560-fb1d5e7f-b3ca-46e9-bdf9-3b48376cec24.png)

Basically, I don't need these `.story.svelte` auto-importing.

**Comment by Mohamed-Kaizen** [comment]
Hi @hallefsantos, update to the latest version and the `exclude` work. [Demo](https://stackblitz.com/edit/sveltejs-kit-template-default-bmc4wn?file=vite.config.js)

**Comment by Mohamed-Kaizen** [comment]
@hallefsantos i will assume the issue has been resolved, closing the issue

**Comment by hallefsantos** [comment]
Thanks @Mohamed-Kaizen, it worked 👍
