### ISSUE TITLE
Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by Wakeful-Cloud** [Mohamed-Kaizen/unplugin-svelte-components#5]
# Issue
When using this plugin, I encounter the below error:
```
Cannot read properties of undefined (reading 'includes')
TypeError: Cannot read properties of undefined (reading 'includes')
    at Context.findComponent (file:///[REDACTED]/node_modules/unplugin-svelte-components/dist/chunk-O26ZTNGK.mjs:25580:19)
    at transformComponent (file:///[REDACTED]/node_modules/unplugin-svelte-components/dist/chunk-O26ZTNGK.mjs:25399:33)
    at async Context.transformer (file:///[REDACTED]/node_modules/unplugin-svelte-components/dist/chunk-O26ZTNGK.mjs:25361:5)
    at async TransformContext.transform (file:///[REDACTED]/node_modules/unplugin-svelte-components/dist/chunk-O26ZTNGK.mjs:25645:22)
    at async Object.transform (file:///[REDACTED]/node_modules/vite/dist/node/chunks/dep-0bae2027.js:41480:30)
    at async loadAndTransform (file:///[REDACTED]/node_modules/vite/dist/node/chunks/dep-0bae2027.js:39287:29)
```

# Expected Behavior
I would expect this plugin to not throw an error.

# Suspected Cause
Filtering modules without ensuring the result isn't undefined ([Possibly here](https://github.com/Mohamed-Kaizen/unplugin-svelte-components/blob/b192edf93844bfe6b1109894e23193b0ae6212f1/src/core/context.ts#L202) and [definitely here](https://github.com/Mohamed-Kaizen/unplugin-svelte-components/blob/b192edf93844bfe6b1109894e23193b0ae6212f1/src/core/context.ts#L210)). Based on some testing I did, this happens when this plugin encounters an import it cannot resolve (Such as with multiple external modules).

# Possible Fix
Return `undefined` if `module` or `cp_name` are `undefined` in `/src/core/context.ts` (The `[0]` array indexes should probably use [the optional chaining operator](https://codeisbae.com/typescript-optional-chaining-nullish-coalescing/)).

# Environment
* `unplugin-svelte-components`: `0.2.2`
* `vite`: `4.0.0`
* NodeJS: `19.2.0`

**Comment by Mohamed-Kaizen** [comment]
Hi @Wakeful-Cloud , thanks for this great report!

Thanks to your report i understood the issue but could i ask you...if you can create a **minimal reproduction** in [stackblitz](https://stackblitz.com/) or github repo, mostly to get more understanding of why this issue happen and when i do try to resolve the issue it will be faster to test it rather than release new version and ask you to try it and tell me if it work for you. Of course the fix that you mention is the correct fix for the issue.

And again thank  this great report :)

**Comment by Mohamed-Kaizen** [comment]
just released new version, please try it and let me know.

**Comment by Wakeful-Cloud** [comment]
[Minimal reproduction](https://stackblitz.com/edit/sveltejs-kit-template-default-gy5fbs). I believe this is fixed and I'll close this issue for now, but I'm not 100% sure because this plugin is still not working (Different error messages; not sure if it's an invalid configuration, another bug, or this bug but with a different error message).

On a different note, version `0.2.3` breaks the documented TypeScript support and I have to import from `unplugin-svelte-components/dist/vite` instead of `unplugin-svelte-components/vite` to regain typing metadata. It appears version `0.2.3` is missing type shims:
```
Directory: [REDACTED]\node_modules\unplugin-svelte-components

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----               [REDACTED                    dist
d-----               [REDACTED                    node_modules
-a----               [REDACTED               1125 LICENSE
-a----               [REDACTED               2807 package.json
-a----               [REDACTED               5105 README.md
```

Version `0.2.2`:
```
Directory: [REDACTED]\node_modules\unplugin-svelte-components

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----               [REDACTED]                   dist
d-----               [REDACTED]                   node_modules
-a----               [REDACTED]                41 esbuild.d.ts
-a----               [REDACTED]                39 index.d.ts
-a----               [REDACTED]              1125 LICENSE
-a----               [REDACTED]              2825 package.json
-a----               [REDACTED]              4954 README.md
-a----               [REDACTED]                40 rollup.d.ts
-a----               [REDACTED]                39 types.d.ts
-a----               [REDACTED]                38 vite.d.ts
-a----               [REDACTED]                41 webpack.d.ts
```

**Comment by Wakeful-Cloud** [comment]
After monkey-patching code related to issue #6, I can confirm this is fixed.
