### ISSUE TITLE
Handling linting errors

### ISSUE THREAD

**Issue by jpaquim** [Mohamed-Kaizen/unplugin-svelte-components#7]
Would it make sense to provide an `.eslintrc-components.json`, similar to what `unplugin-auto-import` does? https://github.com/antfu/unplugin-auto-import#eslint

Otherwise, how should I handle errors from eslint and svelte-check, just disable the `no-undef` rule and rely on TypeScript?

**Comment by Mohamed-Kaizen** [comment]
Hi @jpaquim, i did check the `.eslintrc-components.json` the output will be:

```js

{
	"globals": {
		"myFunction": true
	}
}

```

then i added a component called "Hi" inside the  `.eslintrc-components.json` , and the result is:

```bash

/home/mohamed/Music/scgrp/src/routes/+page.svelte
  1:1  warning  'Hi' is not defined. Consider adding a <script> block with 'export let Hi' to declare a prop  missing-declaration

✖ 1 problem (0 errors, 1 warning)

```


still getting the `missing-declaration` which is from svelte-check, i did try to add rule called `missing-declaration` in eslint....but it's say no such rule.


Sadly  i couldn't find a way to resolve the svelte-check (`missing-declaration`), unlike typescript and eslint....there is no way to tell the svelte-check, "this is the declaration of X, no need to show this as error".


Currently rely on TypeScript is the only way

**Comment by jpaquim** [comment]
I also couldn't find a way around it, other than running `svelte-check` itself with the `--compiler-warnings missing-declaration:ignore` flag. And in VSCode with the following settings.json:
```json
{
	"svelte.plugin.svelte.compilerWarnings": {
		"missing-declaration": "ignore"
	}
}
```
It's a bit heavy handed, but at least it's granular enough to only ignore missing declaration checks.

**Comment by Mohamed-Kaizen** [comment]
yes, that one why to do it, i did recommended in [issue related to that](https://github.com/Mohamed-Kaizen/unplugin-svelte-components/issues/2#issuecomment-1330530558). But i don't recommend this anymore b/c this only silent VScode, if you have anything related or work with `svelte-check` then you will still get an `warning` or `error`, so i highly recommend using `<!-- svelte-ignore missing-declaration -->`.

```svelte
<!-- svelte-ignore missing-declaration -->
<Hi />
```

i know feel ugly to add this to every component but if you have **CI** that depends on `svelte-check`, mostly your CI will never pass , b/c you only silent VScode not `svelte-check`.

Hopefully in the future `svelte-check` will let us add global declaration, until then thanks to everyone reporting this issue🙏 and thanks to everyone using the package 🙏.
